export const CARD_DATA = [
    {
        id: 1,
        sport: "Soccer",
        playerName: "Lionel Messi",
        playerNumber: 10,
        cardDescription: "The exclusive card of vintage barcelona Leo Messi!",
        cardPrice: "$ 599.99",
        averageRating: 4.8,
        numReviews: 3,
        inStock: true,
        isNew: true,
        isAuthentic: true,
        limitedSupply: true,
        cardImage: "https://i.ebayimg.com/images/g/-igAAOSwpdNgl4uO/s-l500.jpg",
        imageCaption: "A picture of Lionel Messi",
        isInCart: false,
        qty: 1
    },
    {
        id: 2,
        sport: "Basketball",
        playerName: "Lebron James",
        playerNumber: 23,
        cardDescription: "The exclusive card of vintage Cav's Lebron!",
        cardPrice: "$ 519.99",
        averageRating: 4.7,
        numReviews: 2,
        inStock: false,
        isNew: true,
        isAuthentic: true,
        limitedSupply: true,
        cardImage: "https://beckett-www.s3.amazonaws.com/news/news-content/uploads/2020/06/2003-04-Upper-Deck-Exquisite-Rookie-Auto-Patch-Parallel-LeBron-James-BGS-9-5-Goldin-July-2020.jpg",
        imageCaption: "A picture of Lebron James",
        isInCart: false,
        qty: 1
    },
    {
        id: 3,
        sport: "Football",
        playerName: "Aaron Rodgers",
        playerNumber: 12,
        cardDescription: "The exclusive card of the GOAT packer Aaron Rodgers!",
        cardPrice: "$ 449.00",
        averageRating: 4.5,
        numReviews: 1,
        inStock: true,
        isNew: false,
        isAuthentic: true,
        limitedSupply: false,
        cardImage: "https://fanatics.frgimages.com/FFImage/thumb.aspx?i=/productimages/_4624000/altimages/ff_4624371-b1790319d6b1c8ecc2d2alt1_full.jpg&w=900",
        imageCaption: "A picture of Aaron Rodgers",
        isInCart: false,
        qty: 1
    },
    {
        id: 4,
        sport: "Soccer",
        playerName: "Cristiano Ronaldo",
        playerNumber: 12,
        cardDescription: "The exclusive card of the second best player of all time! Siuuuu",
        cardPrice: "$ 549.00",
        averageRating: 4.7,
        numReviews: 1,
        inStock: true,
        isNew: true,
        isAuthentic: false,
        limitedSupply: true,
        cardImage: "https://m.media-amazon.com/images/I/61HC7tkFWqL._AC_.jpg",
        imageCaption: "A picture of Cristiano Ronaldo",
        isInCart: false,
        qty: 1
    },
    {
        id: 5,
        sport: "Soccer",
        playerName: "Thierry Henry",
        playerNumber: 14,
        cardDescription: "The exclusive card of the greatest gooner of all time! Henry",
        cardPrice: "$ 569.00",
        averageRating: 4.9,
        numReviews: 2,
        inStock: false,
        isNew: true,
        isAuthentic: true,
        limitedSupply: true,
        cardImage: "https://i.pinimg.com/originals/24/bb/7c/24bb7c3b7d222684e70f572f8407e5e4.jpg",
        imageCaption: "A picture of Theirry Henry",
        isInCart: false,
        qty: 1
    }
]